version: "3.3"

services:
  node:
    image: node:13.12.0-alpine3.11
    # user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - 8080:8080
    command: "npm run server"